### ISSUE TITLE
Latest build failing

### ISSUE THREAD

**Issue by piyush-das** [vuepress-theme-hope/vuepress-theme-hope-template#93]
Hi,

Although npm run serve passes. The page when launched on a localhost shows build failures on the latest template.

![Screenshot from 2020-11-10 12-08-02](https://user-images.githubusercontent.com/68941107/98636792-883bb380-234d-11eb-95dc-83c26fb8eeb2.png)

Thanks

**Comment by Mister-Hope** [comment]
Hi, please submit bugs on main repo instead of on this template.

Also, ci test is on the main repo amd it's passing. So please provide build logs.

**Comment by Mister-Hope** [comment]
https://github.com/Mister-Hope/Mister-Hope.github.io/runs/1378240803?check_suite_focus=true#step:6:1

Could you please run `vuepress serve` with `--clean-cache`?

I don't think there are issues in my code.

**Comment by Mister-Hope** [comment]
By the way, are you using my theme or just this plugin. It may happen it you are not using my theme.

**Comment by piyush-das** [comment]
Hi, I was using the theme. The theme docs instructs to use this template as the starter point. Hence I was using it. I will try running with `--clean-cache` and let you know soon.

**Comment by Mister-Hope** [comment]
I think I found the issues. you should upgrade to 1.5.5.

 You are probably using a lower version of theme with higher version of compont plugin.

 And this is a bug actually.  I should set a default value for navMobileHeight in the component
